# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildAndTestAndPush

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

  # Tests
    - name: Restore dependencies
      run: ./build/prepare.sh 

    - name: Build
      run: ./build/build.sh

    - name: UnitTests
      run: ./build/test.sh

      # if below step is skipped this build is a tag build. Can be used for skipping other steps.
    - name: Is Tag Build
      id: tag
      if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      # Pack and upload to Nuget.org
    - name: Pack and upload to Nuget.org
      if: ${{ steps.tag.conclusion != 'skipped' }}
      run: ./build/nuget.sh 
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      # Create Release Notes
    - name: Create Release Notes
      uses: softprops/action-gh-release@v1
      if: ${{ steps.tag.conclusion != 'skipped' }}
      with:
        generate_release_notes: true
