name: Pull Request CI

on:
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Tests
      - name: Restore dependencies
        run: ./build/prepare.sh

      - name: Build
        run: ./build/build.sh

      - name: UnitTests
        run: ./build/test.sh
